apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: global-ingress
spec:
  profile: empty
  components:
    ingressGateways:
      - name: global-ingress
        enabled: true
        namespace: istio-system
        label:
          ingress: global